name: 'Test Web'
description: 'Runs web frontend CI checks.'
runs:
  using: "composite"
  steps:
    - name: Test web
      shell: bash ./ci/run-ci bash -euo pipefail {0}
      run: cd web && pnpm test
