ALTER TABLE sync_event ADD COLUMN IF NOT EXISTS s3_estimated_cost TEXT DEFAULT NULL;
ALTER TABLE sync_event ADD COLUMN IF NOT EXISTS s3_estimated_cost_currency VARCHAR(8) DEFAULT NULL;
ALTER TABLE sync_event ADD COLUMN IF NOT EXISTS s3_price_profile_id TEXT DEFAULT NULL;
ALTER TABLE sync_event ADD COLUMN IF NOT EXISTS s3_price_catalog_version TEXT DEFAULT NULL;
ALTER TABLE sync_event ADD COLUMN IF NOT EXISTS s3_price_confidence_level TEXT DEFAULT NULL;
ALTER TABLE sync_event ADD COLUMN IF NOT EXISTS s3_price_unknowns JSONB DEFAULT NULL;
ALTER TABLE sync_event ADD COLUMN IF NOT EXISTS s3_price_breakdown JSONB DEFAULT NULL;
