name: 'Build Web'
description: 'Builds the web frontend.'

runs:
  using: "composite"
  steps:
    - name: Sync private web icons
      uses: ./.github/actions/sync_web_icons

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.workspace }}/web
      run: pnpm install --frozen-lockfile

    - name: Build web
      shell: bash
      working-directory: ${{ github.workspace }}/web
      run: pnpm build
